name: Core-Telecom CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r airflow/requirements.txt  
          pip install -r airflow/requirements-ci.txt

      # Validate Airflow DAGs (syntax + imports)
      - name: Validate Airflow DAGs
        run: |
          python -m compileall airflow/dags

      # Install dbt
      - name: Install dbt
        run: |
            pip install dbt-core dbt-snowflake

      # Install dbt dependencies 
      - name: Install dbt dependencies
        run: |
            dbt deps \
            --project-dir dbt/core_telecom_dbt \
            --profiles-dir dbt/core_telecom_dbt/profiles

      # dbt compile (no warehouse connection needed)
      - name: dbt parse
        run: |
          dbt compile \
          --project-dir dbt/core_telecom_dbt \
          --profiles-dir dbt/profiles

      # dbt tests (schema & data tests)
      - name: dbt tests
        run: |
          dbt test \
          --project-dir dbt/core_telecom_dbt \ 
          --profiles-dir dbt/profiles
